name: Bug Report
description: File a bug / issue report
labels: ["bug", "triage"]
assignees:
  - IsCactus0
projects:
  - "IsCactus0/2"
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

      **Make sure to submit separate bug reports if you encountered multiple bugs.**
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen, and what were you doing when it occured?
    placeholder: Tell us what happened!
  validations:
    required: true
- type: dropdown
  id: prevalence
  attributes:
    label: How often does this bug happen?
    options:
      - "Consistently"
      - "Often"
      - "Sometimes"
      - "Rarely"
  validations:
    required: true
- type: upload
  id: screenshots
  attributes:
    label: Upload screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false
